version: '3.8'

volumes:
  postgres_data:

services:
  db:
    image: postgres:14-alpine
    container_name: desafio2_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: persistencia_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  reader:
    image: postgres:14-alpine
    container_name: desafio2_reader
    # o reader espera o db estar pronto
    depends_on:
      - db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: persistencia_db
    # comando para conectar e ler os dados
    command: >
      sh -c "sleep 5 && 
             psql -h db -U user -d persistencia_db -c 'SELECT * FROM dados_persistentes;'"
    networks:
      default:
        aliases:
          - reader_net
