version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: desafio3_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db

  cache:
    image: redis:alpine
    container_name: desafio3_cache
    restart: always

  web:
    build: ./web
    container_name: desafio3_web
    restart: always
    ports:
      - "8080:8080"
    environment:
      CACHE_HOST: cache
      CACHE_PORT: 6379
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
      - cache
